"""Integrated HGSOC showcase narrative report."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

from mbsi.showcase.ovarian_hgsc import SHOWCASE_GUARDRAIL


def generate_ovarian_showcase_report(
    results: Dict[str, Any],
    out_dir: Path = Path("data/outputs"),
) -> Path:
    """Generate integrated HTML narrative report for HGSOC showcase."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    html_path = out_dir / "ovarian_showcase_report.html"

    findings = results.get("findings", {})
    guardrail = results.get("guardrail", SHOWCASE_GUARDRAIL)

    finding_blocks = ""
    for key, f in findings.items():
        finding_blocks += f"""
        <div class="finding">
          <h3>{f.get('label', key)}</h3>
          <p class="hyp">Status: {f.get('hypothesis', 'computational_hypothesis')}</p>
          <ul>
            {''.join(f'<li><strong>{k}:</strong> {v}</li>' for k, v in f.items() if k not in ('label', 'hypothesis'))}
          </ul>
        </div>"""

    comm = results.get("communication", {})
    top_path = comm.get("top_pathway", "N/A")
    tme_summary = results.get("tme", {}).get("summary")
    tme_rows = ""
    if tme_summary is not None and not tme_summary.empty:
        for _, r in tme_summary.iterrows():
            tme_rows += f"<tr><td>{r['niche_type']}</td><td>{int(r['n_spots_detected'])}</td><td>{r['mean_score']:.3f}</td></tr>"

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>HGSOC Showcase Report</title>
<style>
body{{background:#0d1828;color:#f4f7fb;font-family:Georgia,serif;padding:32px;max-width:900px;margin:auto;line-height:1.6}}
h1{{color:#ff4f7b;font-size:1.8rem}}h2{{color:#4f7cff;margin-top:28px}}
.guardrail{{background:#07111f;border-left:4px solid #ffb020;padding:12px 16px;margin:20px 0;color:#9aa7b8}}
.finding{{background:#07111f;border:1px solid #22314a;border-radius:8px;padding:16px;margin:16px 0}}
.hyp{{color:#ffb020;font-size:0.85rem;font-style:italic}}
table{{border-collapse:collapse;width:100%;margin:12px 0}}
th,td{{border:1px solid #22314a;padding:8px}}th{{background:#07111f}}
</style></head><body>
<h1>High-Grade Serous Ovarian Cancer — Flagship Demonstration</h1>
<p><em>MBSI Studio integrated spatial intelligence report</em></p>
<div class="guardrail">{guardrail}</div>
<h2>Executive Summary</h2>
<p>This computational showcase integrates spatial transcriptomics, ligand-receptor communication,
tumor microenvironment niche detection, and platinum/PARP resistance programs on synthetic
HGSOC-like data (seed={results.get('seed', 42)}). All findings are research hypotheses.</p>
<h2>Key Findings</h2>
{finding_blocks}
<h2>Communication Intelligence</h2>
<p>Top ranked pathway: <strong>{top_path}</strong> (computational hypothesis)</p>
<h2>TME Niche Summary</h2>
<table><tr><th>Niche</th><th>Spots</th><th>Mean Score</th></tr>{tme_rows}</table>
<h2>Resistance Programs</h2>
<p>Platinum and PARP resistance signatures scored from reference gene programs (not real ATAC/RNA files).</p>
<p><em>Generated by MBSOC Showcase Pipeline — MBSI Studio</em></p>
</body></html>"""

    html_path.write_text(html)
    (out_dir / "ovarian_showcase_summary.json").write_text(
        json.dumps({
            "disease": results.get("disease"),
            "findings": findings,
            "top_pathway": top_path,
            "guardrail": guardrail,
        }, indent=2, default=str)
    )
    return html_path
