"""Spatial Biomarker Report generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from mbsi.tme.pipeline import TME_GUARDRAIL


def generate_spatial_biomarker_report(
    results: Dict[str, Any],
    out_dir: Path = Path("data/outputs"),
) -> Path:
    """Generate HTML Spatial Biomarker Report (PDF if reportlab available)."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    html_path = out_dir / "spatial_biomarker_report.html"

    summary = results.get("summary")
    biomarkers = results.get("biomarkers")
    guardrail = results.get("guardrail", TME_GUARDRAIL)

    niche_rows = ""
    if summary is not None and not summary.empty:
        for _, r in summary.iterrows():
            niche_rows += (
                f"<tr><td>{r['niche_type']}</td><td>{int(r['n_spots_detected'])}</td>"
                f"<td>{r['mean_score']:.3f}</td><td>{r['hypothesis']}</td></tr>"
            )

    bio_rows = ""
    if biomarkers is not None and not biomarkers.empty:
        for _, r in biomarkers.head(15).iterrows():
            bio_rows += (
                f"<tr><td>{r['gene']}</td><td>{r['niche']}</td>"
                f"<td>{r['correlation']:.3f}</td><td>{r['candidate_score']:.3f}</td></tr>"
            )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Spatial Biomarker Report</title>
<style>
body{{background:#0d1828;color:#f4f7fb;font-family:sans-serif;padding:24px;max-width:960px;margin:auto}}
h1,h2{{color:#4f7cff}}table{{border-collapse:collapse;width:100%;margin:16px 0}}
th,td{{border:1px solid #22314a;padding:8px;text-align:left}}
th{{background:#07111f}}.guardrail{{color:#9aa7b8;font-style:italic;margin:16px 0}}
.hyp{{color:#ffb020;font-size:0.9rem}}
</style></head><body>
<h1>MBSI Studio — Spatial Biomarker Report</h1>
<p class="hyp">Computational hypothesis — pharma-facing outputs require experimental validation.</p>
<p class="guardrail">{guardrail}</p>
<h2>Detected Niches Summary</h2>
<table><tr><th>Niche Type</th><th>Spots Detected</th><th>Mean Score</th><th>Status</th></tr>
{niche_rows}</table>
<h2>Key Biomarker Candidates</h2>
<table><tr><th>Gene</th><th>Associated Niche</th><th>Correlation</th><th>Score</th></tr>
{bio_rows}</table>
<p><em>Generated by MBSI TME Intelligence Engine</em></p>
</body></html>"""

    html_path.write_text(html)

    pdf_path = out_dir / "spatial_biomarker_report.pdf"
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas

        c = canvas.Canvas(str(pdf_path), pagesize=letter)
        y = 750
        c.drawString(50, y, "MBSI Spatial Biomarker Report")
        y -= 20
        for line in guardrail.split(". ")[:2]:
            c.drawString(50, y, line[:90])
            y -= 14
        if summary is not None:
            y -= 10
            for _, r in summary.iterrows():
                c.drawString(50, y, f"{r['niche_type']}: {int(r['n_spots_detected'])} spots, score={r['mean_score']:.3f}")
                y -= 14
                if y < 50:
                    c.showPage()
                    y = 750
        c.save()
    except ImportError:
        pass

    return html_path
